FROM node:19.5.0-alpine AS builder
WORKDIR /usr/src/app
COPY ./ /usr/src/app/
RUN npm install

COPY . .
RUN npm run build

FROM nginx:latest
COPY nginx.conf etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/dist/ /usr/share/nginx/html/




# # Use Node.js LTS version as the base image
# FROM node:18-alpine

# # Set the working directory inside the container
# WORKDIR /app

# # Copy package.json and package-lock.json to the container
# COPY package*.json ./

# # Install dependencies
# RUN npm install

# # Copy all other source code to the container
# COPY . .

# # Build your Vite application
# RUN npm run build

# # Expose the port your app runs on (default for Vite is 3000)
# EXPOSE 5173

# # Serve the app with a production-ready server like serve
# CMD ["npm", "run", "dev"]
